[2023-09-29T22:00:01.612+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_prothomalo scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:00:01.622+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_prothomalo scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:00:01.622+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-09-29T22:00:01.639+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_prothomalo> on 2023-09-29 21:00:00+00:00
[2023-09-29T22:00:01.645+0000] {standard_task_runner.py:57} INFO - Started process 976 to run task
[2023-09-29T22:00:01.648+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_Pipeline', 'extract_prothomalo', 'scheduled__2023-09-29T21:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/news_aggregator_dag.py', '--cfg-path', '/tmp/tmpf86vhjnv']
[2023-09-29T22:00:01.650+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask extract_prothomalo
[2023-09-29T22:00:01.694+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL_Pipeline.extract_prothomalo scheduled__2023-09-29T21:00:00+00:00 [running]> on host 8b9d74f8b315
[2023-09-29T22:00:01.923+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_Pipeline' AIRFLOW_CTX_TASK_ID='extract_prothomalo' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-29T21:00:00+00:00'
[2023-09-29T22:00:01.932+0000] {extract.py:22} ERROR - Could not fetch content due to error: HTTPSConnectionPool(host='www.prothomalo.com', port=443): Max retries exceeded with url: /sitemap.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9112adc310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-09-29T22:00:01.932+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/extract.py", line 35, in parse_from_prothomalo
    latest_sitemap_url = initial_sitemap_soup.find("lastmod").find_next("loc").text
AttributeError: 'NoneType' object has no attribute 'find'
[2023-09-29T22:00:01.941+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_Pipeline, task_id=extract_prothomalo, execution_date=20230929T210000, start_date=20230929T220001, end_date=20230929T220001
[2023-09-29T22:00:01.955+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task extract_prothomalo ('NoneType' object has no attribute 'find'; 976)
[2023-09-29T22:00:01.964+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-29T22:00:01.992+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-29T22:02:44.912+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_prothomalo scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:02:44.924+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_prothomalo scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:02:44.925+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-09-29T22:02:44.966+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_prothomalo> on 2023-09-29 21:00:00+00:00
[2023-09-29T22:02:44.979+0000] {standard_task_runner.py:57} INFO - Started process 1035 to run task
[2023-09-29T22:02:44.985+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_Pipeline', 'extract_prothomalo', 'scheduled__2023-09-29T21:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/news_aggregator_dag.py', '--cfg-path', '/tmp/tmp4v2behzo']
[2023-09-29T22:02:44.990+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask extract_prothomalo
[2023-09-29T22:02:45.071+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL_Pipeline.extract_prothomalo scheduled__2023-09-29T21:00:00+00:00 [running]> on host 8b9d74f8b315
[2023-09-29T22:02:45.218+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_Pipeline' AIRFLOW_CTX_TASK_ID='extract_prothomalo' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-29T21:00:00+00:00'
[2023-09-29T22:02:45.230+0000] {extract.py:22} ERROR - Could not fetch content due to error: HTTPSConnectionPool(host='www.prothomalo.com', port=443): Max retries exceeded with url: /sitemap.xml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9112b37760>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-09-29T22:02:45.231+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/extract.py", line 35, in parse_from_prothomalo
    latest_sitemap_url = initial_sitemap_soup.find("lastmod").find_next("loc").text
AttributeError: 'NoneType' object has no attribute 'find'
[2023-09-29T22:02:45.241+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_Pipeline, task_id=extract_prothomalo, execution_date=20230929T210000, start_date=20230929T220244, end_date=20230929T220245
[2023-09-29T22:02:45.269+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 31 for task extract_prothomalo ('NoneType' object has no attribute 'find'; 1035)
[2023-09-29T22:02:45.318+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-29T22:02:45.358+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-29T22:04:05.136+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_prothomalo scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:04:05.149+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_prothomalo scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:04:05.150+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-09-29T22:04:05.191+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_prothomalo> on 2023-09-29 21:00:00+00:00
[2023-09-29T22:04:05.197+0000] {standard_task_runner.py:57} INFO - Started process 1068 to run task
[2023-09-29T22:04:05.209+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_Pipeline', 'extract_prothomalo', 'scheduled__2023-09-29T21:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/news_aggregator_dag.py', '--cfg-path', '/tmp/tmpdsgror0w']
[2023-09-29T22:04:05.212+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask extract_prothomalo
[2023-09-29T22:04:05.319+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL_Pipeline.extract_prothomalo scheduled__2023-09-29T21:00:00+00:00 [running]> on host 8b9d74f8b315
[2023-09-29T22:04:05.494+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_Pipeline' AIRFLOW_CTX_TASK_ID='extract_prothomalo' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-29T21:00:00+00:00'
[2023-09-29T22:04:06.350+0000] {extract.py:39} INFO - Extracted URLs from Prothom Alo. Total URLs: 256
[2023-09-29T22:04:06.351+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-09-29T22:04:06.358+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=ETL_Pipeline, task_id=extract_prothomalo, execution_date=20230929T210000, start_date=20230929T220405, end_date=20230929T220406
[2023-09-29T22:04:06.404+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-29T22:04:06.424+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-29T22:12:36.518+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_prothomalo scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:12:36.530+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_prothomalo scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:12:36.530+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-09-29T22:12:36.549+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_prothomalo> on 2023-09-29 21:00:00+00:00
[2023-09-29T22:12:36.557+0000] {standard_task_runner.py:57} INFO - Started process 1211 to run task
[2023-09-29T22:12:36.563+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_Pipeline', 'extract_prothomalo', 'scheduled__2023-09-29T21:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/news_aggregator_dag.py', '--cfg-path', '/tmp/tmpmrkwedla']
[2023-09-29T22:12:36.568+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask extract_prothomalo
[2023-09-29T22:12:36.633+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL_Pipeline.extract_prothomalo scheduled__2023-09-29T21:00:00+00:00 [running]> on host 8b9d74f8b315
[2023-09-29T22:12:36.738+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_Pipeline' AIRFLOW_CTX_TASK_ID='extract_prothomalo' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-29T21:00:00+00:00'
[2023-09-29T22:12:37.236+0000] {extract.py:39} INFO - Extracted URLs from Prothom Alo. Total URLs: 256
[2023-09-29T22:12:37.237+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-09-29T22:12:37.250+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=ETL_Pipeline, task_id=extract_prothomalo, execution_date=20230929T210000, start_date=20230929T221236, end_date=20230929T221237
[2023-09-29T22:12:37.271+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-29T22:12:37.296+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-09-29T22:54:43.071+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_prothomalo scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:54:43.086+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_prothomalo scheduled__2023-09-29T21:00:00+00:00 [queued]>
[2023-09-29T22:54:43.086+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-09-29T22:54:43.101+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_prothomalo> on 2023-09-29 21:00:00+00:00
[2023-09-29T22:54:43.107+0000] {standard_task_runner.py:57} INFO - Started process 142 to run task
[2023-09-29T22:54:43.112+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_Pipeline', 'extract_prothomalo', 'scheduled__2023-09-29T21:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/news_aggregator_dag.py', '--cfg-path', '/tmp/tmppzombj5b']
[2023-09-29T22:54:43.116+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask extract_prothomalo
[2023-09-29T22:54:43.175+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL_Pipeline.extract_prothomalo scheduled__2023-09-29T21:00:00+00:00 [running]> on host 4e50881e96f5
[2023-09-29T22:54:43.295+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_Pipeline' AIRFLOW_CTX_TASK_ID='extract_prothomalo' AIRFLOW_CTX_EXECUTION_DATE='2023-09-29T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-29T21:00:00+00:00'
[2023-09-29T22:54:44.140+0000] {extract.py:39} INFO - Extracted URLs from Prothom Alo. Total URLs: 256
[2023-09-29T22:54:44.140+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-09-29T22:54:44.150+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=ETL_Pipeline, task_id=extract_prothomalo, execution_date=20230929T210000, start_date=20230929T225443, end_date=20230929T225444
[2023-09-29T22:54:44.169+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-29T22:54:44.190+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
